# Generated by Django 3.1.5 on 2021-01-26 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('like_count', models.IntegerField(default=0)),
                ('liked_by', models.ManyToManyField(to='core.SystemUser')),
                ('original_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tweets', to='core.systemuser')),
            ],
        ),
        migrations.AddField(
            model_name='systemuser',
            name='retweeted_tweets',
            field=models.ManyToManyField(null=True, to='core.Tweet'),
        ),
    ]
