# Generated by Django 3.1.5 on 2021-01-27 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210127_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('F', 'following'), ('B', 'blocked')], max_length=1)),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user_relationship', to='core.systemuser')),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user_relationship', to='core.systemuser')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('F', 'followed'), ('L', 'liked_tweet'), ('R', 'retweeted')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_owner', to='core.systemuser')),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_second_user', to='core.systemuser')),
            ],
        ),
        migrations.AddField(
            model_name='systemuser',
            name='relationship',
            field=models.ManyToManyField(through='core.RelationShip', to='core.SystemUser'),
        ),
    ]
